import unittest

from cb_terminal.web.server import render_dashboard_html


class DashboardLayoutTests(unittest.TestCase):
    def test_instrument_command_bar_and_assumptions_tab_drive_pm_layout(self):
        html = render_dashboard_html()
        self.assertIn('main class="workbench-layout"', html)
        self.assertIn('nav class="instrument-nav" aria-label="Instrument navigation"', html)
        self.assertIn('id="cb-command-input"', html)
        self.assertIn('class="command-shell"', html)
        self.assertIn('border-radius:14px', html)
        self.assertIn('min-height:54px', html)
        self.assertIn('class="command-prompt">CB&gt;</span>', html)
        self.assertIn('id="cb-command-ghost" class="command-input-ghost" aria-hidden="true"', html)
        self.assertIn('caret-color:#ffd43b', html)
        self.assertIn('.command-input-ghost { position:absolute; inset:7px 0 auto 0;', html)
        self.assertIn('function updateCommandGhost()', html)
        self.assertIn('placeholder="Enter ISIN or display ID"', html)
        self.assertIn('id="cb-command-suggestions" class="command-autocomplete" role="listbox"', html)
        self.assertIn('id="selected-cb-identity"', html)
        self.assertIn('select id="cb-select" class="hidden-select"', html)
        self.assertIn('data-tab="assumptions">Assumptions</button>', html)
        self.assertLess(html.index('data-tab="assumptions"'), html.index('data-tab="pm-view"'))
        self.assertIn('section id="tab-assumptions" class="tab-panel"', html)
        self.assertIn('section class="panel controls-panel" aria-label="Pricing assumptions and controls"', html)
        self.assertIn('grid-template-columns:1fr', html)
        self.assertLess(html.index('id="cb-command-input"'), html.index('section class="plots-panel"'))
        self.assertLess(html.index('data-tab="assumptions"'), html.index('Volatility (%) <input'))
        self.assertLess(html.index('id="active-assumptions-strip"'), html.index('price-chart'))
        self.assertLess(html.index('id="edit-assumptions"'), html.index('price-chart'))
        self.assertGreater(html.index('Volatility (%) <input'), html.index('section id="tab-assumptions"'))

    def test_help_page_explains_cb_terminal_workflow_concisely(self):
        html = render_dashboard_html()
        self.assertIn('data-tab="help">Help</button>', html)
        self.assertIn('section id="tab-help" class="tab-panel"', html)
        self.assertIn('How CB Terminal works', html)
        self.assertIn('Upload source files', html)
        self.assertIn('Extract and approve terms', html)
        self.assertIn('Build valuation history', html)
        self.assertIn('Price and save assumptions', html)
        self.assertNotIn('<li><b>1. Upload source files</b>', html)
        self.assertNotIn('<li><b>2. Extract and approve terms</b>', html)
        self.assertIn('class="workflow-graph" role="img" aria-label="CB Terminal workflow diagram"', html)
        self.assertIn('Prospectus PDF', html)
        self.assertIn('Raw market data', html)
        self.assertIn('Reviewed terms', html)
        self.assertIn('Valuation-ready CSV', html)
        self.assertIn('PM View + Audit', html)
        self.assertIn('Raw files are sources. Valuation-ready CSVs are pricing inputs.', html)
        self.assertIn('Use the command bar to load a CB by ISIN or display ID.', html)
        self.assertIn('Review evidence before approving extracted terms.', html)
        self.assertLess(html.index('data-tab="help">Help</button>'), html.index('section id="tab-help"'))

    def test_pm_view_exposes_implied_volatility_failure_explanation(self):
        html = render_dashboard_html()
        self.assertIn('id="iv-diagnostics"', html)
        self.assertIn('function renderImpliedVolatilityDiagnostics(payload)', html)
        self.assertIn('Implied volatility unavailable', html)
        self.assertIn('No bond market price was supplied', html)
        self.assertIn('Target bond price is outside the solver range', html)
        self.assertIn('renderImpliedVolatilityDiagnostics(payload);', html)

    def test_plots_use_plain_matlab_style_svg_not_card_dashboard_chrome(self):
        html = render_dashboard_html()
        self.assertIn('class="matlab-plot"', html)
        self.assertIn('stroke-width="2"', html)
        self.assertIn('text-anchor="middle"', html)
        self.assertIn('Yield curve used as risk-free rate', html)
        self.assertIn('background:#000; border:1px solid #555', html)
        self.assertNotIn('box-shadow', html)
        self.assertNotIn('linear-gradient', html)

    def test_plots_are_compact_enough_to_reduce_scroll_capture(self):
        html = render_dashboard_html()
        self.assertIn('svg.matlab-plot { width:100%; min-height:240px;', html)
        self.assertIn('svg.matlab-plot.small-plot { min-height:160px; }', html)
        self.assertIn('svg.matlab-plot.pm-plot { min-height:220px; }', html)
        self.assertIn('svg.matlab-plot.pm-small-plot { min-height:145px; }', html)
        self.assertIn('id="price-chart" class="matlab-plot pm-plot" viewBox="0 0 900 220"', html)
        self.assertIn('id="volatility-overlay-chart" class="matlab-plot pm-plot" viewBox="0 0 900 220"', html)
        self.assertIn('id="raw-quote-chart" class="matlab-plot" viewBox="0 0 900 240"', html)
        self.assertIn('id="valuation-cheapness-mini-chart" class="matlab-plot small-plot pm-small-plot" viewBox="0 0 900 160"', html)
        self.assertIn('id="rv-stock-chart" class="matlab-plot small-plot pm-small-plot" viewBox="0 0 900 160"', html)
        self.assertNotIn('min-height:280px', html)
        self.assertNotIn('min-height:190px', html)

    def test_chart_wheel_zoom_does_not_capture_normal_page_scroll(self):
        html = render_dashboard_html()
        self.assertIn('class="chart-gesture-hint"', html)
        self.assertIn('Scroll page normally; hold Ctrl/⌘ or Alt while scrolling over a chart to zoom', html)
        self.assertIn('function isChartWheelZoomGesture(event)', html)
        self.assertIn('return Boolean(event.ctrlKey || event.metaKey || event.altKey);', html)
        self.assertIn('if (!isChartWheelZoomGesture(event)) return;\n    event.preventDefault();', html)

    def test_prospectus_extract_selected_uses_raw_pdf_selection_and_data_upload_owns_upload(self):
        html = render_dashboard_html()
        data_upload_idx = html.index('data-tab="data-intake">Data Upload</button>')
        prospectus_intake_idx = html.index('data-tab="prospectus-intake">Prospectus Intake</button>')
        extract_selected_idx = html.index('id="extract-selected-prospectuses"')
        self.assertLess(data_upload_idx, prospectus_intake_idx)
        self.assertLess(prospectus_intake_idx, extract_selected_idx)
        self.assertIn('data-upload-input="upload-prospectus"', html)
        self.assertIn('data-upload-kind="market_data_auto" data-upload-input="upload-market-data"', html)
        self.assertIn('Detects CB quote history, equity history, FX history, valuation-ready history, or mixed files', html)
        self.assertNotIn('data-upload-input="upload-raw-price"', html)
        self.assertNotIn('data-upload-kind="market_data_history"', html)
        self.assertNotIn('data-upload-kind="market_history_csv"', html)
        self.assertNotIn('data-upload-input="upload-prospectus-inbox"', html)
        self.assertNotIn('id="inbox-upload-status"', html)
        self.assertIn('id="extract-selected-prospectuses" class="prospectus-action-button cmd-primary" aria-label="Extract selected PDFs" title="Select one or more raw PDFs before extraction" disabled>Extract selected (0)</button>', html)
        self.assertIn('<input type="checkbox" name="raw-pdf-row"', html)
        self.assertNotIn('<input type="radio" name="raw-pdf-row"', html)
        self.assertIn("const selectedCount = selectedSourcePaths().length;", html)
        self.assertIn("selectedButton.disabled = extractionRunning || selectedCount === 0;", html)
        self.assertIn("filter(item => item && (reviewBucket(item) === 'pending_extraction' || !item.contract_path))", html)
        self.assertIn("selectedReviewIndexes = selectedReviewItem ? new Set([selectedIndex]) : new Set();", html)
        self.assertIn("function toggleReviewSelection(index, event={})", html)
        self.assertIn("event.shiftKey", html)

    def test_pending_raw_delete_can_resolve_filename_only_queue_rows(self):
        html = render_dashboard_html()
        self.assertIn("function selectedRawSourcePath()", html)
        self.assertIn("return selectedReviewItem?.source_path || selectedReviewItem?.source_file || (selectedReviewItem?.source_filename ? `data/raw/prospectuses/${selectedReviewItem.source_filename}` : '');", html)

    def test_progress_ui_is_reusable_for_prospectus_and_data_source_linking(self):
        html = render_dashboard_html()
        self.assertIn('id="extraction-progress" class="progress-wrap"', html)
        self.assertIn('id="source-link-progress" class="progress-wrap"', html)
        self.assertIn('id="source-link-progress-text"', html)
        self.assertIn("function setProgressBar(config, active, text='', percent=0)", html)
        self.assertIn("setProgressBar(PROGRESS_COMPONENTS.extraction", html)
        self.assertIn("setProgressBar(PROGRESS_COMPONENTS.sourceLink", html)
        self.assertIn("setSourceActionControls(true)", html)
        self.assertIn("setSourceActionControls(false)", html)
        self.assertLess(html.index('id="generate-valuation-history"'), html.index('id="source-link-progress"'))

    def test_terms_review_buttons_use_compact_command_group_style(self):
        html = render_dashboard_html()
        terms_idx = html.index('data-prospectus-subtab="terms">Terms / Evidence / Actions</button>')
        group_idx = html.index('class="intake-action-row command-group terms-action-group" aria-label="Terms review actions"')
        approve_idx = html.index('id="approve-contract-terms" class="cmd-primary" aria-label="Approve terms for pricing" title="Approve terms for pricing">Approve</button>')
        save_idx = html.index('id="save-contract-terms" aria-label="Save edits; keep in review" title="Save edits; keep in review">Save edits</button>')
        reload_idx = html.index('id="load-contract-review" class="cmd-utility" aria-label="Reload terms for selected CB" title="Reload terms for selected CB">Reload</button>')
        self.assertLess(terms_idx, group_idx)
        self.assertLess(group_idx, approve_idx)
        self.assertLess(approve_idx, save_idx)
        self.assertLess(save_idx, reload_idx)
        self.assertIn('<span class="command-label">TERMS</span>', html)
        self.assertNotIn('>Approve terms for pricing</button>', html)
        self.assertNotIn('>Save edits; keep in review</button>', html)
        self.assertNotIn('>Reload terms for selected CB</button>', html)

    def test_assumption_action_buttons_use_compact_command_group_style(self):
        html = render_dashboard_html()
        group_idx = html.index('class="button-row intake-action-row command-group assumption-action-group" aria-label="Pricing assumption actions"')
        preview_idx = html.index('type="submit" class="cmd-primary" aria-label="Run price preview" title="Run non-persistent price preview">Price Preview</button>')
        refresh_idx = html.index('id="refresh-selected-cb" class="cmd-utility" aria-label="Refresh selected CB and price" title="Reload selected CB paths and price if ready">Refresh CB + price</button>')
        save_idx = html.index('id="save-assumptions" aria-label="Save assumption set" title="Save current assumptions as an append-only set">Save Assumption Set</button>')
        self.assertLess(group_idx, preview_idx)
        self.assertLess(preview_idx, refresh_idx)
        self.assertLess(refresh_idx, save_idx)
        self.assertIn('<span class="command-label">PRICE</span>', html)
        self.assertIn('.intake-action-row.command-group', html)
        self.assertIn('.intake-action-row button { padding:6px 9px; min-height:28px; font-size:14px;', html)

    def test_assumptions_form_starts_empty_without_prefilled_values(self):
        html = render_dashboard_html()

        self.assertIn('name="volatility" type="number" step="0.01"></label>', html)
        self.assertIn('name="risk_free_rate" type="hidden">', html)
        self.assertIn('name="credit_spread" type="number" step="1"></label>', html)
        self.assertIn('name="borrow_rate" type="number" step="0.01"></label>', html)
        self.assertIn('name="dividend_yield" type="number" step="0.01"></label>', html)
        self.assertIn('name="steps" type="number" min="3" max="500"></label>', html)
        self.assertIn('<option value="">Select model...</option>', html)
        self.assertIn('name="scenario_name"></label>', html)
        self.assertIn('Manual fallback RF / yield curve display (%)', html)
        self.assertIn('name="manual_rf_display" type="number" step="0.01" oninput=', html)
        self.assertIn('name="contract_path"></label>', html)
        self.assertIn('name="market_history_path"></label>', html)
        self.assertIn('name="raw_price_history_path"></label>', html)
        self.assertIn('name="use_yield_curve" type="checkbox" value="1"><span>Use internet yield curve', html)
        self.assertNotIn('name="use_yield_curve" type="checkbox" value="1" checked', html)
        self.assertNotIn('value="38"', html)
        self.assertNotIn('value="160"', html)
        self.assertNotIn('value="250"', html)
        self.assertNotIn('value="base"', html)
        self.assertNotIn('<option value="tf_split_tree" selected>', html)

    def test_yield_curve_override_is_visible_in_dashboard_copy_and_outputs(self):
        html = render_dashboard_html()

        self.assertIn('matched curve yield is the risk-free rate', html)
        self.assertIn('Curve target', html)
        self.assertIn('Risk-free source', html)
        self.assertIn('yield-curve-chart', html)
        self.assertIn('Matched maturity', html)

    def test_yield_curve_chart_uses_tenor_scaled_x_axis_and_clamped_match_marker(self):
        html = render_dashboard_html()

        self.assertIn("xValueKey:'years'", html)
        self.assertIn("xLabel:'Tenor (years)'", html)
        self.assertIn("function clampPlotX(value, xMin, xMax)", html)
        self.assertIn("const markerYears = clampPlotX(Number(latest.target_years), minX, maxX);", html)
        self.assertIn("const x = value =>", html)
        self.assertIn("shown at available curve edge", html)
        self.assertNotIn("const x = v => P.left + (Number(v)-minX)/xSpan*(W-P.left-P.right);", html)

    def test_dashboard_html_contains_cb_terminal_branding_without_legacy_names(self):
        html = render_dashboard_html()
        self.assertIn("CB Terminal", html)
        self.assertIn("Local CB valuation workbench.", html)
        self.assertNotIn("Bloomberg-style local terminal", html)
        forbidden = ["CB " + "Arb", "CB " + "Arbi" + "trage", "cb" + "-arb", "cb" + "_arb", "Cb" + "Arb"]
        for old_name in forbidden:
            self.assertNotIn(old_name, html)

    def test_data_sources_use_professional_market_source_actions(self):
        html = render_dashboard_html()
        self.assertIn('CB quote, stock, and FX history', html)
        self.assertIn('id="refresh-source-matches"', html)
        self.assertIn('Refresh matches', html)
        self.assertIn('id="generate-valuation-history"', html)
        self.assertIn('Generate valuation CSV', html)
        self.assertIn('Used by / coverage', html)
        self.assertIn('FX sources are global', html)
        self.assertIn("async function generateValuationHistory()", html)
        self.assertIn("function activeContractPath()", html)
        self.assertIn("if (raw === ''", html)
        self.assertIn("contract_path:contractPath", html)
        self.assertIn("payload.status === 'no_overlap'", html)
        self.assertIn("fetch('/api/market-generation-readiness'", html)
        self.assertIn('id="market-generation-readiness"', html)
        self.assertIn("renderMarketGenerationReadiness", html)
        self.assertIn("fetch('/api/generate-valuation-market-history'", html)
        self.assertNotIn('id="link-source"', html)
        self.assertNotIn('Link to selected CB', html)
        self.assertNotIn("payload.sync_status === 'linked_to_selected_cb'", html)

    def test_cb_refresh_and_data_source_linking_reprice_selected_contract(self):
        html = render_dashboard_html()

        self.assertIn('id="refresh-selected-cb"', html)
        self.assertIn('Refresh CB + price', html)
        self.assertIn("document.getElementById('refresh-selected-cb').addEventListener('click', refreshSelectedCb);", html)
        self.assertIn("async function refreshSelectedCb()", html)
        self.assertIn("async function refreshActiveInstrumentTabs(options={})", html)
        self.assertIn("await refreshActiveInstrumentTabs({source:'command'});", html)
        self.assertIn("cbSelect.addEventListener('change', () => { applySelectedCb(); refreshActiveInstrumentTabs(); });", html)
        self.assertIn("await loadPricing();\n  await loadSources();\n  await loadReviewQueue({preferredContractPaths:[contractPath]});\n  await syncSelectedContractReviewFromDropdown();\n  await loadMarketGenerationReadiness();", html)
        self.assertIn("Loaded ${label} across PM View, Assumptions, Data Sources, and Prospectus Intake.", html)
        self.assertIn("await loadUniverse({preferredContractPaths:[selected.contract_path], price:false});", html)
        self.assertIn("clearPricingView(", html)
        self.assertIn("latestPayload = null;", html)
        self.assertIn("function pricingReadinessMessage(selected)", html)
        self.assertIn("const readiness = selected?.readiness ||", html)
        self.assertIn("missing.includes('valuation_market_history')", html)
        self.assertIn("raw quotes linked; generate market history", html)
        self.assertIn("SQLite source", html)
        self.assertIn("Canonical source id", html)
        self.assertIn("function cbDisplayLabel(item)", html)
        self.assertIn("return item.display_id || item.instrument_display_name", html)
        self.assertIn("esc(cbDisplayLabel(item))", html)
        self.assertIn("const label = cbDisplayLabel(selected);", html)
        self.assertIn("async function generateValuationHistory()", html)
        self.assertIn("function activeContractPath()", html)
        self.assertIn("if (raw === ''", html)
        self.assertIn("contract_path:contractPath", html)
        self.assertIn("payload.status === 'no_overlap'", html)
        self.assertIn("fetch('/api/market-generation-readiness'", html)
        self.assertIn('id="market-generation-readiness"', html)
        self.assertIn("renderMarketGenerationReadiness", html)
        self.assertIn("fetch('/api/generate-valuation-market-history'", html)
        self.assertIn("payload.source_link", html)
        self.assertNotIn("payload.sync_status === 'linked_to_selected_cb'", html)
        self.assertLess(html.index('id="refresh-selected-cb"'), html.index('id="save-assumptions"'))
        self.assertIn("function selectCbFromCommand(raw)", html)
        self.assertIn("function cbSearchText(item)", html)
        self.assertIn("function renderCbCommandSuggestions(query='')", html)
        self.assertIn("function commandCompletionCandidate(query)", html)
        self.assertIn("function acceptCommandGhostCompletion()", html)
        self.assertIn("event.key === 'Tab' && acceptCommandGhostCompletion()", html)
        self.assertIn("cbCommandInput.setAttribute('aria-activedescendant'", html)
        self.assertIn('position:relative; border-top:1px solid #222', html)
        self.assertIn("function handleCbCommandKeydown(event)", html)
        self.assertIn("function selectCbByIndex(idx)", html)
        self.assertIn("if (!selected) { clearPricingView('Enter ISIN or display ID to load a CB.'); statusEl.textContent = 'No CB loaded.'; return; }", html)
        self.assertIn("statusEl.textContent = universeItems.length ? 'Coverage universe loaded. Enter an ISIN or display ID.' : 'No covered CBs loaded.';", html)
        self.assertNotIn("selectedIndex = universeItems.findIndex(item => item.available_for_pricing);", html)


if __name__ == "__main__":
    unittest.main()
